// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoZz6JfpUItlTLIdUkzJWHAxkq3xHHbAA',
    appId: '1:665489454042:web:270d2cbd668c2e33e506e3',
    messagingSenderId: '665489454042',
    projectId: 'edupresence-3803d',
    authDomain: 'edupresence-3803d.firebaseapp.com',
    storageBucket: 'edupresence-3803d.firebasestorage.app',
    measurementId: 'G-CY79MPTBW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVgCzBneAjirRSHZiZa4czx1sczz3npU',
    appId: '1:665489454042:android:0a171d194f26a832e506e3',
    messagingSenderId: '665489454042',
    projectId: 'edupresence-3803d',
    storageBucket: 'edupresence-3803d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk6PxiUqTEZrQjaOriVYpNzeDgqzECfmM',
    appId: '1:665489454042:ios:b030635f45f19ac5e506e3',
    messagingSenderId: '665489454042',
    projectId: 'edupresence-3803d',
    storageBucket: 'edupresence-3803d.firebasestorage.app',
    iosBundleId: 'com.example.edupresence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk6PxiUqTEZrQjaOriVYpNzeDgqzECfmM',
    appId: '1:665489454042:ios:b030635f45f19ac5e506e3',
    messagingSenderId: '665489454042',
    projectId: 'edupresence-3803d',
    storageBucket: 'edupresence-3803d.firebasestorage.app',
    iosBundleId: 'com.example.edupresence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoZz6JfpUItlTLIdUkzJWHAxkq3xHHbAA',
    appId: '1:665489454042:web:c0e3280ced29d2dfe506e3',
    messagingSenderId: '665489454042',
    projectId: 'edupresence-3803d',
    authDomain: 'edupresence-3803d.firebaseapp.com',
    storageBucket: 'edupresence-3803d.firebasestorage.app',
    measurementId: 'G-708GTBPQRV',
  );
}
